"""make job url unique

Revision ID: 27af957896f1
Revises: 9b7c3ed0c3a7
Create Date: 2026-09-10 18:50:56.023850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27af957896f1'
down_revision: Union[str, Sequence[str], None] = '9b7c3ed0c3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'jobs', ['job_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='unique')
    # ### end Alembic commands ###
