"""add job status

Revision ID: 3d72b4b982ea
Revises: 841d240a4dd1
Create Date: 2026-08-27 00:50:45.063328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d72b4b982ea'
down_revision: Union[str, Sequence[str], None] = '841d240a4dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status', sa.String(length=50), nullable=False, server_default='SAVED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'status')
    # ### end Alembic commands ###
